language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t roman1975/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true roman1975/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "docker-react-aws"
  env: "DockerReactAws-env"
  bucket_name: "elasticbeanstalk-eu-west-1-083839949526"
  bucket_path: "docker-react-aws"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY