language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t Roman1975/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true Roman1975/docker-react npm run test -- --coverage